export const AUTH_START  = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL  = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const GET_PROFILE_START = "GET_PROFILE_START";
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const GET_PROFILE_FAIL = "GET_PROFILE_FAIL";

export const UPDATE_PROFILE_START = "UPDATE_PROFILE_START";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_FAIL ="UPDATE_PROFILE_FAIL";

 
export const STUDENT_COURSE_START = "STUDENT_COURSE_START";
export const STUDENT_COURSE_SUCCESS = "STUDENT_COURSE_SUCCESS";
export const STUDENT_COURSE_FAIL = "STUDENT_COURSE_FAIL";

export const GET_SELECTED_CHAPTERS_START = "GET_SELECTED_CHAPTERS_START" ;
export const GET_SELECTED_CHAPTERS_SUCCESS = "GET_SELECTED_CHAPTERS_SUCCESS" ;
export const GET_SELECTED_CHAPTERS_FAIL = "GET_SELECTED_CHAPTERS_FAIL" ;

export const GET_SELECTED_TOPIC_START = "GET_SELECTED_TOPIC_START" ;
export const GET_SELECTED_TOPIC_SUCCESS = "GET_SELECTED_TOPIC_SUCCESS" ;
export const GET_SELECTED_TOPIC_FAIL = "GET_SELECTED_TOPIC_FAIL" ;
